### ISSUE TITLE
Fullscreen not Working

### ISSUE THREAD

**Issue by nabulator** [Deltafire/MilkyTracker#16]
I'm using the ubuntu ppa version.
When I turn on fullscreen via command line, the initial splash image is fullscreen, then upon showing the actual tracker the program quickly turns into windows mode.

**Comment by dwhinham** [comment]
In the upcoming SDL2 port (on my github fork) some fullscreen-related stuff may have been improved, so it may be worth compiling and testing it. Failing that, perhaps I can build you a binary package for you to try?

**Comment by Deltafire** [comment]
This still occurs in the latest SDL2 build.

**Comment by dwhinham** [comment]
This behaviour is because the '-fullscreen' command line option - while successfully setting the window to be fullscreen - does not update the tracker config file. After the splash screen finishes, the tracker startup reads in and applies the settings in the config file. Because the config file value for "FULLSCREEN" now differs from the current state of the window, the window is taken back out of fullscreen to match the value in the config file.

To fix this, I suggest we add another bool to Tracker::startup() so that if we want to request fullscreen via the command line, the config file value for fullscreen mode is ignored. I'll prepare a patch tomorrow perhaps :)

**Comment by Deltafire** [comment]
The -fullscreen code is old, it predates version control and I think was added before the config option. It may have only been put there for testing, I can't think why it would be needed now.

**Comment by nabulator** [comment]
Well, I kinda wanted to use it to make it fullscreen... It looks more like fasTracker. I believe fullscreen also makes video capture easier. Schism tracker supports fullscreen as well.

**Comment by dwhinham** [comment]
Deltafire's saying it's not needed because you can easily switch to fullscreen mode by pressing ALT-ENTER, or by going into the settings screen and ticking the Fullscreen option. You may need to use one of the small ">" arrows next to the settings category in order to see the fullscreen option. Once you do this, MT will always start up in fullscreen mode as it's stored in the config.

**Comment by nabulator** [comment]
lol, my right alt key is broken for some reason.
sorry for the confusion.
