### ISSUE TITLE
Cocoa: Can't drag and drop files into Milkytracker

### ISSUE THREAD

**Issue by Deltafire** [Deltafire/MilkyTracker#19]

**Comment by dwhinham** [comment]
You can if you're running my local version :) I'll have some commits for this ASAP.

**Comment by dwhinham** [comment]
Almost ready to commit a fix for this. :) Taken a bit longer because I wanted to implement the nice blue border effect that OSX does when you drag things over a drop target. Had to write some stuff to manually plot the pixels as well as save and restore what's under them. The result is quite nice and works well in the flesh:

<img width="812" alt="screen shot 2015-07-16 at 23 10 34" src="https://cloud.githubusercontent.com/assets/5890747/8738333/9b5a50a4-2c25-11e5-9da9-f1c841a597b2.png">

**Comment by Deltafire** [comment]
My OSX doesn't have a blue border effect when drag & dropping :cry:

**Comment by dwhinham** [comment]
You don't find it everywhere, but it's found in a few places, like drag and drop onto Finder windows:
![drag_from_inactive_2x](https://cloud.githubusercontent.com/assets/5890747/8743321/986163de-2c65-11e5-9029-ee2ac8aeefbf.png)

It's a grey border if you switched to the grey colour theme in system preferences - my code uses a fucntion to get the colour from the system. :)

[Apple say](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/DragDrop.html):
> Highlight the destination region as soon as the pointer enters it and stop highlighting when the pointer leaves the region. If there are multiple destination regions within a window, highlight one destination region at a time.

...so this is what I'm trying to achieve :smiley:
