### ISSUE TITLE
Windows: WaveOut/MMSYSTEM driver has major flaws

### ISSUE THREAD

**Issue by dwhinham** [Deltafire/MilkyTracker#31]
The first problem with the driver is that some types are being used incorrectly for setting up the callback. Namely, the call to ``waveOutOpen()`` casts the callback function to a ``DWORD`` when this should be ``DWORD_PTR``. On 32bit builds we may get away with this; on 64bit builds we lose precision and end up crashing. This is trivial to fix.

The second, more serious problem is that system calls are present within the callback function, which is not allowed and causes deadlocks.

From [MSDN](https://msdn.microsoft.com/en-us/library/dd743869(v=vs.85).aspx):
> Applications should not call any system-defined functions from inside a callback function, except for EnterCriticalSection, LeaveCriticalSection, midiOutLongMsg, midiOutShortMsg, OutputDebugString, PostMessage, PostThreadMessage, SetEvent, timeGetSystemTime, timeGetTime, timeKillEvent, and timeSetEvent. Calling other wave functions will cause deadlock.

The driver needs refactoring to correct this, so I am investigating a fix. We should also look at more modern APIs like XAudio2, which from briefly Googling is a replacement for DirectSound.

**Comment by Deltafire** [comment]
Could we use RtAudio to handle all audio on Windows?

**Comment by sagamusix** [comment]
RtAudio only suppports DSound and ASIO on Windows, which is a pretty incomplete collection: 
- DSound is deprecated and only emulated since Vista. DSound can lead to random problems (at least observed with OpenMPT and XMPlay).
- ASIO is entirely optional and many people don't have an ASIO driver at all.

WaveOut is by far the most compatible and widespread API and thus works well as a fallback, but of course (actually just like DSound) comes with drawbacks like high latency.

The modern way to go would be to support WASAPI, which allows for relatively low latencies in non-exclusive mode, but also supports a low-latency exclusive device access mode, practically like KernelStreaming on XP and WaveRT on Vista/newer. RtAudio does not support WASAPI.

PortAudio supports all these APIs and is cross-platform like RtAudio. It might be worth replacing RtAudio by PortAudio, but it's worth keeping in mind that PortAudio has its own issues here and there (but I'm sure RtAudio has some as well): We've run into problems like PortAudio returning completely bogus latency values for some APIs, or even only under some conditions (e.g. WASAPI in exclusive mode). It's all fixable or workaroundable, but one needs to be aware that it's not bug-free.

**Comment by dwhinham** [comment]
Thanks for the info about PortAudio. There has been some PortAudio source in MilkyTracker for a while, but I don't think we've built it for Windows.

RtAudio actually added WASAPI support according to their GitHub repo: https://github.com/thestk/rtaudio

Still, I think I'd like to attempt a new custom driver for Windows; Core Audio fixed up nicely in the end for the Mac port. I'd personally enjoy the exercise as audio programming interests me. :smiley:

It looks like XAudio2 sits on top of WASAPI, so it probably makes sense to just go straight to WASAPI for the best possible shot at low-latency under Windows.

I'll try to fix up the WaveOut driver as a fallback, and see what we can do about using WASAPI.

**Comment by Deltafire** [comment]
> I'd personally enjoy the exercise as audio programming interests me.

I was wondering why I bothered making Alsa & Jack drivers for Linux instead of just using SDL, I guess that was the reason!

**Comment by dwhinham** [comment]
:+1: :+1: :+1: 
Apart from that, as someone uses music software too, there's nothing worse than high latency when you are trying to write a tune or play live. It'd be great to give MilkyTracker the best possible options for audio output so that musicians don't have to put up with rubbish audio. :smiley:

**Comment by dwhinham** [comment]
I'm pleased to report that I've got a fix for WaveOut!

Got rid of the callback mechanism and instead moved to a thread signalling mechanism. Needs plenty testing but we should be good. :smiley:

**Comment by Deltafire** [comment]
Fixed in commit 6be13e1.
