### ISSUE TITLE
Windows: Drag & Drop only works with recognised file extensions

### ISSUE THREAD

**Issue by Deltafire** [Deltafire/MilkyTracker#38]
Subbi mentioned this at Sundown.

**Comment by dwhinham** [comment]
In Cocoa I didn't intend to allow dragging unrecognised file formats, but are we saying it's a pretty useful feature for loading arbitrary data as samples, etc?

If so, I agree - let's give this to Windows users too.

**Comment by Deltafire** [comment]
I think the main problem is Amiga modules have traditionally been named “mod.filename” instead of “filename.mod” - and they still are named this way.  At the moment they have to be drag-dropped in Cocoa, and loaded using the file dialog only on Windows.

**Comment by sagamusix** [comment]
Can't reproduce this on Windows, would be weird anyway because that's not how a simple Drag&Drop handler should work. Here I can just throw any renamed mod file at Milky and it loads it - which is sensible for the reason Deltafire mentioned (also because there are many different extensions for the same old formats, e.g. M15/NST/etc. for old 15-sample MODs.

**Comment by dwhinham** [comment]
Can we clarify what needs to be done, then (if anything)? :smiley:

**Comment by sagamusix** [comment]
Asking Subi for steps to reproduce, because from what I can tell Milky's Drag&Drop integration works as intended on Windows.

**Comment by subi211** [comment]
Okay, this is quite embarrassing, but I can't actually repro the problem now.  :(
I'd only noticed it recently, so I must've just been clumsy and dragged the file over the wrong part of the screen, because you're right, it'll accept any file.  Sorry for that.  O__o

**Comment by Deltafire** [comment]
No worries!  This makes it an easy fix :)
