### ISSUE TITLE
Remove internal rtmidi

### ISSUE THREAD

**Issue by Deltafire** [Deltafire/MilkyTracker#43]
The Fedora build package uses the system installed rtmidi instead of the internal copy.

Consider removing the internal version of rtmidi and use the system version instead.

Note: The Fedora patch would have to be extended with configure checks.

**Comment by dwhinham** [comment]
:+1:

rtmidi is available in [OS X Homebrew](http://braumeister.org/formula/rtmidi) as well as Ubuntu via apt-get on 14.04 LTS, so this would probably be a sensible move.

Not sure what the nicest way of getting library dependencies on Windows is... hmm.

**Comment by muep** [comment]
The patch currently in Fedora is indeed just a very minimal change that works with how Fedora is laid out but not necessarily e.g. on OS X. The focus initially was just to get the package reasonably up to date.

Longer-term, it would be preferable to have as few patches as possible in the Fedora packaging. Thus having at least built-in capability of using the system-provided rtmidi would be very welcome.

**Comment by dwhinham** [comment]
@muep: I've staged a variation of the patch the Debian/Ubuntu guys were using (attributed to you) at c3c651cc95bd3a243779ee67a66114e8874ecfb2, along with other patches to allow use of system zziplib and lhasa from @jcowgill.

These need testing with different distros, and I'm also concentrating on a new CMake-based build system to replace the current Automake one, which also makes use of these patches so that under Linux and OS X we can use system-provided libs where possible.

Thanks for contributing! :)
