### ISSUE TITLE
SDL2 Linux bad key bindings

### ISSUE THREAD

**Issue by 44100hertz** [Deltafire/MilkyTracker#47]
Simply put, I'm a dvorak user, and notes are put in seemingly random places unless I switch to qwerty.

I'm using SDL2+Linux

**Comment by 44100hertz** [comment]
I just confirmed that on both my laptop and desktop, regardless of layout it still results in a wrong and very random layout.

Going back to before the sdl2 branch was merged does fix this problem.

**Comment by dwhinham** [comment]
Hi @44100hertz,

Can you try after compiling with -DNOT_PC_KB=1?
There's a hack present from SDL1 code that looks like it's no longer required in SDL2.

Cheers!
-Dale

**Comment by 44100hertz** [comment]
Okay, I tried it. Works fine but only in qwerty; dvorak is disorganized in an expected way. (typing "qwerty" in dvorak gives a scale).

**Comment by dwhinham** [comment]
Great - so that's half the issue. Obviously we will need to handle key input differently for entering notes. I'll get onto this shortly - thanks for the report.  :)

**Comment by 44100hertz** [comment]
Alright, I was messing with this some more. Using the latest with no extra cflags:
1. The numbers act correctly as black keys...but for the bottom octave.
2. A-J in alphabetical order act as black keys for the top octave, where the number keys would be
3. M-X act as the top row Q-Z
4. -, +, [, ], \ act as part of the bottom white octave

so, funny enough I can still compose if I really think about it :stuck_out_tongue_winking_eye:

**Comment by dwhinham** [comment]
Thanks for the extra info. I'll have a crack at this over the weekend I think, would be nice to get some of these keyboard bugs fixed as it's a major usability issue. :+1:

**Comment by dwhinham** [comment]
I've attempted a fix at this - could you please checkout ``issue_47`` and test it? :smiley: 
You shouldn't need to compile with ``-DNOT_PC_KB=1`` either.

Cheers!

**Comment by 44100hertz** [comment]
Works for me on any layout, identical side-by-side with the stable!
Thank you for the great work.

**Comment by dwhinham** [comment]
Thanks for testing, Sam! :smiley:

I've done a bit more work on keyboard handling. I noticed that entering '+' in the volume column was not possible with UK layout under SDL/Linux, because '+' is a shifted character (Shift + '=').

There's another branch called ``keyboard_fixes`` now, with another patch that's independant of this one.

I accidentally based the ``issue_47`` branch off of another branch (``cmake_split``) when I meant to base it off ``master``, so I've had to do a force push to fix this.

It'd be really helpful if you could try the following:
```
# Get the lastest branches etc from GitHub
git fetch

# Switch back to master
git checkout master

# Delete the old issue_47 branch
git branch -D issue_47

# Re-checkout the new issue_47 branch which now has a different history
git checkout -b issue_47 origin/issue_47

# Add the patch from the keyboard_fixes branch
git cherry-pick origin/keyboard_fixes
```

And finally build, run, and see if everything works as expected. In particular, make sure you can enter ``-``/``+`` in the volume column.

Many thanks again! :smiley:

**Comment by 44100hertz** [comment]
Ah, I hadn't noticed that! Guess I was primarily testing the piano, not the rest of the bindings. Yes, even on US and US dvorak layouts, + and - were not working before, but are now working after the keyboard fixes.

And of course, I'm glad to help testing one of my favorite trackers.
